<?php

namespace Cyberdean\Security\BotDetectBundle\Repository\Security;

/**
 * BadUserAgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadUserAgentRepository extends \Doctrine\ORM\EntityRepository
{
}
