<?php

namespace Cyberdean\Security\BotDetectBundle\Repository\Security;
use Cyberdean\Security\BotDetectBundle\Doctrine\RegExp;
use Cyberdean\Security\BotDetectBundle\Entity\Security\BadUrl;
use Doctrine\ORM\EntityRepository;

/**
 * BadUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadUrlRepository extends EntityRepository
{
    /**
     * Check if an url match regexp
     * @param $url string Url to test
     * @return null|BadUrl
     */
    public function matchUrl($url) {
        $qb = $this->createQueryBuilder('b');

        $qb->getEntityManager()->getConfiguration()->addCustomStringFunction('REGEXP', function () {
            return new RegExp('REGEXP');
        });

        $qb->where('REGEXP(:testUrl, b.url) = true')
            ->setMaxResults(1)
            ->setParameter('testUrl', $url);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
