<?php

namespace Cyberdean\Security\BotDetectBundle\Repository\Security;
use Cyberdean\Security\BotDetectBundle\Doctrine\RegExp;

/**
 * BadUserAgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadUserAgentRepository extends \Doctrine\ORM\EntityRepository
{
    public function matchUA($ua) {
        $qb = $this->createQueryBuilder('b');

        $qb->getEntityManager()->getConfiguration()->addCustomStringFunction('REGEXP', function () {
            return new RegExp('REGEXP');
        });

        $qb->where('REGEXP(:testUa, b.ua) = true')
            ->setMaxResults(1)
            ->setParameter('testUa', $ua);
        $qb->getQuery()->getOneOrNullResult();
    }
}
