<?php

namespace Cyberdean\Security\BotDetectBundle\Repository\Security;

/**
 * BadUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadUrlRepository extends \Doctrine\ORM\EntityRepository
{

}
